--1.모든 레코드 구하기
SELECT *
FROM ANIMAL_INS
ORDER BY 1 ASC;

--2.역순 정렬하기
SELECT NAME, DATETIME
FROM ANIMAL_INS
ORDER BY ANIMAL_ID DESC;

--3.아픈 동물 찾기
SELECT ANIMAL_ID, NAME
FROM ANIMAL_INS
WHERE INTAKE_CONDITION = 'Sick';

--4.어린 동물 찾기
SELECT ANIMAL_ID, NAME
FROM ANIMAL_INS
WHERE INTAKE_CONDITION <> 'Aged';

--5.동물의 아이디와 이름
SELECT ANIMAL_ID, NAME
FROM ANIMAL_INS;

--6.여러 기준으로 정렬하기
SELECT ANIMAL_ID, NAME, DATETIME
FROM ANIMAL_INS
ORDER BY 2,3 DESC;

--7.상위 n개 레코드
SELECT NAME
FROM ANIMAL_INS
WHERE DATETIME <= ALL(SELECT DATETIME
                      FROM ANIMAL_INS);
                      
--8.최댓값 구하기
SELECT DATETIME
FROM ANIMAL_INS
WHERE DATETIME >= ALL(SELECT DATETIME FROM ANIMAL_INS)

--9.최솟값 구하기
SELECT DATETIME
FROM ANIMAL_INS
WHERE DATETIME <= ALL(SELECT DATETIME FROM ANIMAL_INS)

--10.동물 수 구하기
SELECT COUNT(*) AS COUNT
FROM ANIMAL_INS

--11.중복 제거하기
SELECT COUNT(DISTINCT NAME) AS COUNT
FROM ANIMAL_INS
WHERE NAME IS NOT NULL;

--12.고양이와 개는 몇 마리 있을까
SELECT ANIMAL_TYPE, COUNT(*) AS COUNT
FROM ANIMAL_INS
WHERE ANIMAL_TYPE IN ('Dog', 'Cat')
GROUP BY ANIMAL_TYPE
ORDER BY ANIMAL_TYPE ASC;

--13.동명 동물 수 찾기
SELECT NAME, COUNT(NAME) AS COUNT
FROM ANIMAL_INS
GROUP BY NAME
HAVING COUNT(NAME) >=2
ORDER BY NAME;

--14.입양 시각 구하기(1)
SELECT HOUR(DATETIME) AS HOUR, COUNT(*) AS COUNT 
FROM ANIMAL_OUTS
WHERE HOUR(DATETIME)>8 AND HOUR(DATETIME)<20
GROUP BY HOUR(DATETIME) 
ORDER BY HOUR(DATETIME);
                      
                      
