--1.오랜 기간 보호한 동물(2)
SELECT A.ANIMAL_ID, A.NAME
FROM ANIMAL_OUTS A
JOIN ANIMAL_INS B ON A.ANIMAL_ID = B.ANIMAL_ID
ORDER BY TIMESTAMPDIFF(DAY, B.DATETIME, A.DATETIME) DESC
LIMIT 2;

--2.DATETIME에서 DATE로 형 변환
SELECT ANIMAL_ID, NAME, DATE_FORMAT(DATETIME, '%Y-%m-%d') AS 날짜
FROM ANIMAL_INS
ORDER BY ANIMAL_ID;

--3.헤비 유저가 소유한 장소
SELECT A.ID, A.NAME, A.HOST_ID
FROM PLACES A
JOIN (SELECT * FROM PLACES GROUP BY HOST_ID HAVING COUNT(HOST_ID)>1) B
ON A.HOST_ID = B.HOST_ID
ORDER BY 1;

--4.우유와 요거트가 담긴 장바구니
SELECT CART_ID
FROM CART_PRODUCTS
WHERE NAME IN ('Milk', 'Yogurt')
GROUP BY CART_ID
HAVING COUNT(DISTINCT NAME) > 1;
