--1.입양시각 구하기(1)
SELECT HOUR(DATETIME) AS HOUR, COUNT(*) AS COUNT FROM ANIMAL_OUTS
WHERE HOUR(DATETIME)>8 AND HOUR(DATETIME)<20
GROUP BY HOUR(DATETIME) ORDER BY HOUR(DATETIME);

--2.입양시각 구하기(2) ★
SELECT HOUR, IFNULL(COUNT,0) AS COUNT
FROM (
SELECT @N := @N + 1 AS HOUR FROM ANIMAL_OUTS,
(SELECT @N := -1 FROM DUAL)NN LIMIT 24
) AS A
LEFT JOIN (
SELECT HOUR(DATETIME) AS HR, COUNT(*) AS COUNT
FROM ANIMAL_OUTS
GROUP BY HR
) AS B
ON A.HOUR = b.HR

--3.이름이 없는 동물의 아이디
SELECT ANIMAL_ID
FROM ANIMAL_INS
WHERE ISNULL(NAME)
ORDER BY ANIMAL_ID ASC;

--4.이름이 있는 동물의 아이디
SELECT ANIMAL_ID
FROM ANIMAL_INS
WHERE NAME IS NOT NULL
ORDER BY ANIMAL_ID;

--5.NULL 처리하기
SELECT ANIMAL_TYPE, CASE WHEN NAME IS NULL THEN 'No name' ELSE NAME END AS 'NAME', SEX_UPON_INTAKE
FROM ANIMAL_INS

